version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: accounting
      POSTGRES_PASSWORD: accounting
      POSTGRES_DB: accounting
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: gunicorn src.config.wsgi:application --bind 0.0.0.0:8000
    env_file: backend/.env
    volumes:
      - ./backend:/code
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm run preview -- --host
    env_file: frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
volumes:
  db-data:
